spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hospital_familia_dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hospital_familia_dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hospital_familia_dev}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

app.docs.enabled=${APP_DOCS_ENABLED:true}
app.demo.seed-enabled=${APP_DEMO_SEED_ENABLED:false}
management.endpoint.health.show-details=${MANAGEMENT_HEALTH_SHOW_DETAILS:always}
springdoc.swagger-ui.enabled=${APP_DOCS_ENABLED:true}
springdoc.api-docs.enabled=${APP_DOCS_ENABLED:true}
