CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    link_code VARCHAR(40) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_patients_public_id UNIQUE (public_id),
    CONSTRAINT uk_patients_link_code UNIQUE (link_code)
);

CREATE TABLE tutor_patient_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    decided_by_user_id BIGINT,
    decision_reason VARCHAR(280),
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    decided_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_tutor_patient_link UNIQUE (tutor_id, patient_id),
    CONSTRAINT fk_tutor_patient_links_tutor FOREIGN KEY (tutor_id) REFERENCES app_users (id),
    CONSTRAINT fk_tutor_patient_links_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_tutor_patient_links_decider FOREIGN KEY (decided_by_user_id) REFERENCES app_users (id),
    CONSTRAINT ck_tutor_patient_links_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'REVOKED'))
);

CREATE INDEX idx_tutor_patient_links_tutor_status ON tutor_patient_links (tutor_id, status);
CREATE INDEX idx_tutor_patient_links_status ON tutor_patient_links (status);
CREATE INDEX idx_tutor_patient_links_patient ON tutor_patient_links (patient_id);
