CREATE TABLE patient_care_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    care_status VARCHAR(80) NOT NULL,
    current_service VARCHAR(120),
    current_location VARCHAR(120),
    summary VARCHAR(220),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_patient_care_snapshots_patient UNIQUE (patient_id),
    CONSTRAINT fk_patient_care_snapshots_patient FOREIGN KEY (patient_id) REFERENCES patients (id)
);

CREATE INDEX idx_patient_care_snapshots_updated_at ON patient_care_snapshots (updated_at);
