CREATE TABLE patient_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    title VARCHAR(140) NOT NULL,
    description VARCHAR(500),
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    estimated_duration_minutes INTEGER,
    service VARCHAR(120),
    location VARCHAR(120),
    responsible_staff VARCHAR(160),
    created_by_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_patient_events_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_patient_events_creator FOREIGN KEY (created_by_user_id) REFERENCES app_users (id),
    CONSTRAINT ck_patient_events_type CHECK (event_type IN ('SURGERY', 'EXAM', 'VISIT', 'STATE_CHANGE', 'DISCHARGE', 'OTHER')),
    CONSTRAINT ck_patient_events_status CHECK (status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX idx_patient_events_patient_scheduled_at ON patient_events (patient_id, scheduled_at);
CREATE INDEX idx_patient_events_status ON patient_events (status);
